---
title: "1 - Data Management"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

### Setup

```{r}
#| include: false
#| label: Setup
library(tidyverse)
library(readxl)
```

### Input file

```{r}
#| label: input_file
ds <- read_xlsx("data/topfruitspublic.xlsx")
```

### Explore

```{r}
glimpse(ds)
```

### Fix date

```{r}
ds <- ds |> mutate(date = as.Date(date, origin = "1899-12-30"))
```

### Check missing values

```{r}
colSums(is.na(ds))
```

### Checking the table

```{r}
head(ds)
```

### TIDY: pivot fruit choices to long format

```{r}
ds_long <- ds |>
  select(name, age, gender, diet_type, first, second, third, first_confidence,	second_confidence,	third_confidence,	reasoning,	seasonal,	distaste
 ) |>
  pivot_longer(cols = c(first, second, third),
               names_to  = "rank",
               values_to = "fruit") |>
  drop_na(fruit)

```

### Checking the tidy table

```{r}
ds_long |> head() |> print(width = Inf)
```

### Summarise

```{r}
ds_long |>
  count(fruit, sort = TRUE)

ds_long |>
  count(diet_type, fruit, sort = TRUE)
```

### Output file

```{r}
write_csv(ds_long, "1_datamanagement_files/fruits_long.csv")
```
